upstream django_server {
    server web:8000;
}

server {
    listen 80;

    # Statik dosyalar için (Paylaşılan klasörden okunacak)
    location /static/ {
        alias /app/staticfiles/;
    }

    # Dinamik sayfalar için (Django'ya gönderilecek)
    location / {
        proxy_pass http://django_server;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}